part of 'pr_data.dart';

const flutterPRs = <PullRequest>[
  PullRequest(
    title: '''un-break `ThemeData` equality''',
    url: '''https://github.com/flutter/flutter/pull/154695''',
    diffs: (357, 561),
    refactor: true,
  ),
  PullRequest(
    title: '''Refactor `CircularNotchedRectangle.getOuterPath()`''',
    url: '''https://github.com/flutter/flutter/pull/154036''',
    diffs: (22, 31),
    refactor: true,
  ),
  PullRequest(
    title: '''Fix `Drawer` prematurely snapping''',
    url: '''https://github.com/flutter/flutter/pull/153955''',
    diffs: (68, 1),
    refactor: false,
  ),
  PullRequest(
    title: '''`_InteractiveViewerState` code cleanup''',
    url: '''https://github.com/flutter/flutter/pull/153645''',
    diffs: (83, 134),
    refactor: true,
  ),
  PullRequest(
    title: '''Factor out `Container` objects''',
    url: '''https://github.com/flutter/flutter/pull/153619''',
    diffs: (420, 347),
    refactor: true,
  ),
  PullRequest(
    title: '''Add Nate Wilson to authors''',
    url: '''https://github.com/flutter/flutter/pull/152907''',
    diffs: (1, 0),
    refactor: false,
  ),
  PullRequest(
    title: '''Implement `on` clauses''',
    url: '''https://github.com/flutter/flutter/pull/152706''',
    diffs: (22, 36),
    refactor: true,
  ),
  PullRequest(
    title: '''Use `.fromMap()` constructors in example code''',
    url: '''https://github.com/flutter/flutter/pull/152535''',
    diffs: (67, 102),
    refactor: true,
  ),
  PullRequest(
    title: '''Style Guide updates''',
    url: '''https://github.com/flutter/flutter/pull/152525''',
    diffs: (106, 103),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing null-aware logic in `/packages/flutter/`''',
    url: '''https://github.com/flutter/flutter/pull/152294''',
    diffs: (159, 298),
    refactor: true,
  ),
  PullRequest(
    title: '''`MaterialState` → `WidgetState` in documentation''',
    url: '''https://github.com/flutter/flutter/pull/151376''',
    diffs: (508, 510),
    refactor: false,
  ),
  PullRequest(
    title: '''Factor out deprecated names in example code''',
    url: '''https://github.com/flutter/flutter/pull/151374''',
    diffs: (80, 80),
    refactor: false,
  ),
  PullRequest(
    title: '''Update `DataTable` documentation''',
    url: '''https://github.com/flutter/flutter/pull/151356''',
    diffs: (28, 18),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing a few switch statements''',
    url: '''https://github.com/flutter/flutter/pull/150946''',
    diffs: (107, 175),
    refactor: true,
  ),
  PullRequest(
    title: '''Add a message about spam/brigading''',
    url: '''https://github.com/flutter/flutter/pull/150583''',
    diffs: (2, 2),
    refactor: false,
  ),
  PullRequest(
    title: '''Fix breakages introduced by `SplashFactory`''',
    url: '''https://github.com/flutter/packages/pull/6952''',
    diffs: (12, 12),
    refactor: false,
  ),
  PullRequest(
    title: '''`dismissible.dart` code cleanup''',
    url: '''https://github.com/flutter/flutter/pull/150276''',
    diffs: (34, 33),
    refactor: true,
  ),
  PullRequest(
    title: '''Fix markdown hyperlinks in the style guide''',
    url: '''https://github.com/flutter/flutter/pull/150071''',
    diffs: (82, 88),
    refactor: false,
  ),
  PullRequest(
    title: '''Reland "Update `FocusManager` platform check to include iOS"''',
    url: '''https://github.com/flutter/flutter/pull/148984''',
    diffs: (47, 48),
    refactor: false,
  ),
  PullRequest(
    title: '''`switch` expressions: finale''',
    url: '''https://github.com/flutter/flutter/pull/148711''',
    diffs: (214, 466),
    refactor: true,
  ),
  PullRequest(
    title: '''Reland "`if` chains → `switch` expressions"''',
    url: '''https://github.com/flutter/flutter/pull/148634''',
    diffs: (194, 297),
    refactor: true,
  ),
  PullRequest(
    title: '''Fix template manifest test''',
    url: '''https://github.com/flutter/flutter/pull/148616''',
    diffs: (2, 3),
    refactor: false,
  ),
  PullRequest(
    title: '''Implement new `AnimationStatus` getters''',
    url: '''https://github.com/flutter/flutter/pull/148570''',
    diffs: (221, 384),
    refactor: true,
  ),
  PullRequest(
    title: '''`switch` statement cleanup''',
    url: '''https://github.com/flutter/flutter/pull/148382''',
    diffs: (301, 529),
    refactor: true,
  ),
  PullRequest(
    title: '''Enhanced enum features for `AnimationStatus`''',
    url: '''https://github.com/flutter/flutter/pull/147801''',
    diffs: (175, 3),
    refactor: false,
  ),
  PullRequest(
    title: '''`flutter/lib/src/`: refactoring if-chains into switch expressions''',
    url: '''https://github.com/flutter/flutter/pull/147472''',
    diffs: (195, 275),
    refactor: true,
  ),
  PullRequest(
    title: '''Control flow collections: `flutter_tools/`''',
    url: '''https://github.com/flutter/flutter/pull/147450''',
    diffs: (221, 459),
    refactor: true,
  ),
  PullRequest(
    title: '''Getting rid of containers''',
    url: '''https://github.com/flutter/flutter/pull/147432''',
    diffs: (480, 428),
    refactor: true,
  ),
  PullRequest(
    title: '''Refactor `Material` build method''',
    url: '''https://github.com/flutter/flutter/pull/147430''',
    diffs: (37, 92),
    refactor: true,
  ),
  PullRequest(
    title: '''Add default arguments to `AnimatedPhysicalModel`''',
    url: '''https://github.com/flutter/flutter/pull/147424''',
    diffs: (49, 11),
    refactor: false,
  ),
  PullRequest(
    title: '''Switch to relevant `Remote` constructors''',
    url: '''https://github.com/flutter/flutter/pull/146773''',
    diffs: (15, 51),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing control flow collections''',
    url: '''https://github.com/flutter/flutter/pull/146601''',
    diffs: (276, 494),
    refactor: true,
  ),
  PullRequest(
    title: '''`flutter/lib/src/`: refactoring if-chains into switch expressions''',
    url: '''https://github.com/flutter/flutter/pull/146293''',
    diffs: (111, 203),
    refactor: true,
  ),
  PullRequest(
    title: '''`WidgetState` mapping''',
    url: '''https://github.com/flutter/flutter/pull/146043''',
    diffs: (305, 10),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing switch expressions in `flutter_tools/`''',
    url: '''https://github.com/flutter/flutter/pull/145632''',
    diffs: (222, 409),
    refactor: true,
  ),
  PullRequest(
    title: '''Intensive `if` chain refactoring''',
    url: '''https://github.com/flutter/flutter/pull/145194''',
    diffs: (98, 352),
    refactor: true,
  ),
  PullRequest(
    title: '''Turning `if` chains into shorter `switch` statements''',
    url: '''https://github.com/flutter/flutter/pull/144977''',
    diffs: (141, 182),
    refactor: true,
  ),
  PullRequest(
    title: '''Refactoring `if` chains into `switch` statements''',
    url: '''https://github.com/flutter/flutter/pull/144905''',
    diffs: (404, 349),
    refactor: true,
  ),
  PullRequest(
    title: '''Add platform check to `FocusManager` app lifecycle listener''',
    url: '''https://github.com/flutter/flutter/pull/144718''',
    diffs: (51, 6),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing switch expressions in `flutter/test/`''',
    url: '''https://github.com/flutter/flutter/pull/144580''',
    diffs: (115, 189),
    refactor: true,
  ),
  PullRequest(
    title: '''Add missing parameter to `TableBorder.symmetric`, and improve class constructors''',
    url: '''https://github.com/flutter/flutter/pull/144279''',
    diffs: (196, 357),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in `rendering/`''',
    url: '''https://github.com/flutter/flutter/pull/143812''',
    diffs: (366, 604),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing null-aware operators throughout the repository''',
    url: '''https://github.com/flutter/flutter/pull/143804''',
    diffs: (93, 365),
    refactor: true,
  ),
  PullRequest(
    title: '''Allow `Listenable.merge()` to use any iterable''',
    url: '''https://github.com/flutter/flutter/pull/143675''',
    diffs: (20, 5),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions: everything in `flutter/lib/src/`''',
    url: '''https://github.com/flutter/flutter/pull/143634''',
    diffs: (503, 925),
    refactor: true,
  ),
  PullRequest(
    title: '''Implement `_suspendedNode` fix''',
    url: '''https://github.com/flutter/flutter/pull/143556''',
    diffs: (2, 3),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions [refactoring `flutter/lib/src/`]''',
    url: '''https://github.com/flutter/flutter/pull/143496''',
    diffs: (152, 305),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in `widgets/`''',
    url: '''https://github.com/flutter/flutter/pull/143293''',
    diffs: (169, 306),
    refactor: true,
  ),
  PullRequest(
    title: '''Have `FocusManager` respond to app lifecycle state changes''',
    url: '''https://github.com/flutter/flutter/pull/142930''',
    diffs: (102, 0),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in `lib/src/material/`''',
    url: '''https://github.com/flutter/flutter/pull/142793''',
    diffs: (182, 339),
    refactor: true,
  ),
  PullRequest(
    title: '''Implement `switch` expressions in `lib/src/material/`''',
    url: '''https://github.com/flutter/flutter/pull/142634''',
    diffs: (146, 256),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in `foundation/` and `material/`''',
    url: '''https://github.com/flutter/flutter/pull/142279''',
    diffs: (115, 196),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in the `cupertino/` directory''',
    url: '''https://github.com/flutter/flutter/pull/141591''',
    diffs: (78, 144),
    refactor: true,
  ),
  PullRequest(
    title: '''Implement `switch` expressions in `examples/` and `animation/`''',
    url: '''https://github.com/flutter/flutter/pull/139882''',
    diffs: (33, 50),
    refactor: true,
  ),
  PullRequest(
    title: '''Implement `switch` expressions in `dev/`''',
    url: '''https://github.com/flutter/flutter/pull/139048''',
    diffs: (117, 197),
    refactor: true,
  ),
];
