part of 'pr_data.dart';

const flutterPRs = <PullRequest>[
  PullRequest(
    title: '''[two_dimensional_scrollables] prepare for `const AnimationStyle`''',
    url: '''https://github.com/flutter/packages/pull/8397''',
    date: 'Jan 08 2025',
    diffs: (6, 0),
    refactor: false,
  ),
  PullRequest(
    title: '''[CP-stable] Revert "Fix DropdownMenu does not rematch initialSelection when entries have changed"''',
    url: '''https://github.com/flutter/flutter/pull/161177''',
    date: 'Jan 06 2025',
    diffs: (61, 198),
    refactor: false,
  ),
  PullRequest(
    title: '''`ImplicitlyAnimatedWidgetState` code cleanup''',
    url: '''https://github.com/flutter/flutter/pull/160567''',
    date: 'Dec 19 2024',
    diffs: (10, 25),
    refactor: true,
  ),
  PullRequest(
    title: '''`const AnimationStyle`''',
    url: '''https://github.com/flutter/flutter/pull/160564''',
    date: 'Dec 19 2024',
    diffs: (117, 114),
    refactor: false,
  ),
  PullRequest(
    title: '''Fix `Stepper` connector not being properly displayed''',
    url: '''https://github.com/flutter/flutter/pull/160193''',
    date: 'Dec 12 2024',
    diffs: (81, 8),
    refactor: false,
  ),
  PullRequest(
    title: '''Fix `SafeArea` DartPad sample''',
    url: '''https://github.com/flutter/flutter/pull/159344''',
    date: 'Nov 22 2024',
    diffs: (31, 2),
    refactor: false,
  ),
  PullRequest(
    title: '''Merge queue screenshots''',
    url: '''https://github.com/flutter/assets-for-api-docs/pull/254''',
    date: 'Nov 15 2024',
    diffs: (0, 0),
    refactor: false,
  ),
  PullRequest(
    title: '''Add `SafeArea` DartPad sample''',
    url: '''https://github.com/flutter/flutter/pull/158019''',
    date: 'Nov 01 2024',
    diffs: (379, 6),
    refactor: false,
  ),
  PullRequest(
    title: '''Fix `NestedScrollView` inner position logic''',
    url: '''https://github.com/flutter/flutter/pull/157756''',
    date: 'Oct 28 2024',
    diffs: (117, 1),
    refactor: false,
  ),
  PullRequest(
    title: '''Factor out "shaker" class''',
    url: '''https://github.com/flutter/flutter/pull/157748''',
    date: 'Oct 28 2024',
    diffs: (31, 49),
    refactor: true,
  ),
  PullRequest(
    title: '''Fix `ResizeImage` documentation''',
    url: '''https://github.com/flutter/flutter/pull/157619''',
    date: 'Oct 25 2024',
    diffs: (9, 7),
    refactor: false,
  ),
  PullRequest(
    title: '''Add `@protected` to public `State` method overrides''',
    url: '''https://github.com/flutter/flutter/pull/157313''',
    date: 'Oct 22 2024',
    diffs: (223, 5),
    refactor: false,
  ),
  PullRequest(
    title: '''`WidgetStateInputBorder`''',
    url: '''https://github.com/flutter/flutter/pull/157190''',
    date: 'Oct 18 2024',
    diffs: (349, 0),
    refactor: false,
  ),
  PullRequest(
    title: '''Arrow syntax for getters''',
    url: '''https://github.com/flutter/flutter/pull/156483''',
    date: 'Oct 09 2024',
    diffs: (240, 346),
    refactor: true,
  ),
  PullRequest(
    title: '''Inherited Theme: zero rebuilds''',
    url: '''https://github.com/flutter/flutter/pull/155699''',
    date: 'Sep 25 2024',
    diffs: (105, 0),
    refactor: false,
  ),
  PullRequest(
    title: '''Show issues in triage even if they've been assigned''',
    url: '''https://github.com/flutter/flutter/pull/155615''',
    date: 'Sep 24 2024',
    diffs: (2, 2),
    refactor: false,
  ),
  PullRequest(
    title: '''Refactor devfs_web_ddc_modules_test.dart''',
    url: '''https://github.com/flutter/flutter/pull/155609''',
    date: 'Sep 24 2024',
    diffs: (1334, 1574),
    refactor: true,
  ),
  PullRequest(
    title: '''Monomorphic Mapper''',
    url: '''https://github.com/flutter/flutter/pull/154972''',
    date: 'Sep 11 2024',
    diffs: (263, 85),
    refactor: false,
  ),
  PullRequest(
    title: '''pattern-matching refactor''',
    url: '''https://github.com/flutter/flutter/pull/154753''',
    date: 'Sep 06 2024',
    diffs: (380, 673),
    refactor: true,
  ),
  PullRequest(
    title: '''un-break `ThemeData` equality''',
    url: '''https://github.com/flutter/flutter/pull/154695''',
    date: 'Sep 05 2024',
    diffs: (357, 561),
    refactor: true,
  ),
  PullRequest(
    title: '''"Fix failing checks" wiki page for new contributors''',
    url: '''https://github.com/flutter/flutter/pull/154629''',
    date: 'Sep 04 2024',
    diffs: (140, 0),
    refactor: false,
  ),
  PullRequest(
    title: '''Fix `WidgetStateProperty` documentation''',
    url: '''https://github.com/flutter/flutter/pull/154298''',
    date: 'Aug 28 2024',
    diffs: (74, 109),
    refactor: false,
  ),
  PullRequest(
    title: '''Refactor `CircularNotchedRectangle.getOuterPath()`''',
    url: '''https://github.com/flutter/flutter/pull/154036''',
    date: 'Aug 23 2024',
    diffs: (22, 31),
    refactor: true,
  ),
  PullRequest(
    title: '''Fix `Drawer` prematurely snapping''',
    url: '''https://github.com/flutter/flutter/pull/153955''',
    date: 'Aug 22 2024',
    diffs: (68, 1),
    refactor: false,
  ),
  PullRequest(
    title: '''`_InteractiveViewerState` code cleanup''',
    url: '''https://github.com/flutter/flutter/pull/153645''',
    date: 'Aug 18 2024',
    diffs: (83, 134),
    refactor: true,
  ),
  PullRequest(
    title: '''Factor out `Container` objects''',
    url: '''https://github.com/flutter/flutter/pull/153619''',
    date: 'Aug 17 2024',
    diffs: (420, 347),
    refactor: true,
  ),
  PullRequest(
    title: '''Add Nate Wilson to authors''',
    url: '''https://github.com/flutter/flutter/pull/152907''',
    date: 'Aug 06 2024',
    diffs: (1, 0),
    refactor: false,
  ),
  PullRequest(
    title: '''Implement `on` clauses''',
    url: '''https://github.com/flutter/flutter/pull/152706''',
    date: 'Aug 01 2024',
    diffs: (22, 36),
    refactor: true,
  ),
  PullRequest(
    title: '''Use `.fromMap()` constructors in example code''',
    url: '''https://github.com/flutter/flutter/pull/152535''',
    date: 'Jul 30 2024',
    diffs: (67, 102),
    refactor: true,
  ),
  PullRequest(
    title: '''Style Guide updates''',
    url: '''https://github.com/flutter/flutter/pull/152525''',
    date: 'Jul 30 2024',
    diffs: (106, 103),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing null-aware logic in `/packages/flutter/`''',
    url: '''https://github.com/flutter/flutter/pull/152294''',
    date: 'Jul 25 2024',
    diffs: (159, 298),
    refactor: true,
  ),
  PullRequest(
    title: '''`MaterialState` → `WidgetState` in documentation''',
    url: '''https://github.com/flutter/flutter/pull/151376''',
    date: 'Jul 06 2024',
    diffs: (508, 510),
    refactor: false,
  ),
  PullRequest(
    title: '''Factor out deprecated names in example code''',
    url: '''https://github.com/flutter/flutter/pull/151374''',
    date: 'Jul 06 2024',
    diffs: (80, 80),
    refactor: false,
  ),
  PullRequest(
    title: '''Update `DataTable` documentation''',
    url: '''https://github.com/flutter/flutter/pull/151356''',
    date: 'Jul 05 2024',
    diffs: (28, 18),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing a few switch statements''',
    url: '''https://github.com/flutter/flutter/pull/150946''',
    date: 'Jun 27 2024',
    diffs: (107, 175),
    refactor: true,
  ),
  PullRequest(
    title: '''Add a message about spam/brigading''',
    url: '''https://github.com/flutter/flutter/pull/150583''',
    date: 'Jun 20 2024',
    diffs: (2, 2),
    refactor: false,
  ),
  PullRequest(
    title: '''Fix breakages introduced by `SplashFactory`''',
    url: '''https://github.com/flutter/packages/pull/6952''',
    date: 'Jun 19 2024',
    diffs: (12, 12),
    refactor: false,
  ),
  PullRequest(
    title: '''`dismissible.dart` code cleanup''',
    url: '''https://github.com/flutter/flutter/pull/150276''',
    date: 'Jun 14 2024',
    diffs: (34, 33),
    refactor: true,
  ),
  PullRequest(
    title: '''Fix markdown hyperlinks in the style guide''',
    url: '''https://github.com/flutter/flutter/pull/150071''',
    date: 'Jun 11 2024',
    diffs: (82, 88),
    refactor: false,
  ),
  PullRequest(
    title: '''Reland "Update `FocusManager` platform check to include iOS"''',
    url: '''https://github.com/flutter/flutter/pull/148984''',
    date: 'May 23 2024',
    diffs: (47, 48),
    refactor: false,
  ),
  PullRequest(
    title: '''`switch` expressions: finale''',
    url: '''https://github.com/flutter/flutter/pull/148711''',
    date: 'May 20 2024',
    diffs: (214, 466),
    refactor: true,
  ),
  PullRequest(
    title: '''Reland "`if` chains → `switch` expressions"''',
    url: '''https://github.com/flutter/flutter/pull/148634''',
    date: 'May 19 2024',
    diffs: (194, 297),
    refactor: true,
  ),
  PullRequest(
    title: '''Fix template manifest test''',
    url: '''https://github.com/flutter/flutter/pull/148616''',
    date: 'May 18 2024',
    diffs: (2, 3),
    refactor: false,
  ),
  PullRequest(
    title: '''Implement new `AnimationStatus` getters''',
    url: '''https://github.com/flutter/flutter/pull/148570''',
    date: 'May 17 2024',
    diffs: (221, 384),
    refactor: true,
  ),
  PullRequest(
    title: '''`switch` statement cleanup''',
    url: '''https://github.com/flutter/flutter/pull/148382''',
    date: 'May 15 2024',
    diffs: (301, 529),
    refactor: true,
  ),
  PullRequest(
    title: '''Enhanced enum features for `AnimationStatus`''',
    url: '''https://github.com/flutter/flutter/pull/147801''',
    date: 'May 03 2024',
    diffs: (175, 3),
    refactor: false,
  ),
  PullRequest(
    title: '''`flutter/lib/src/`: refactoring if-chains into switch expressions''',
    url: '''https://github.com/flutter/flutter/pull/147472''',
    date: 'Apr 27 2024',
    diffs: (195, 275),
    refactor: true,
  ),
  PullRequest(
    title: '''Control flow collections: `flutter_tools/`''',
    url: '''https://github.com/flutter/flutter/pull/147450''',
    date: 'Apr 27 2024',
    diffs: (221, 459),
    refactor: true,
  ),
  PullRequest(
    title: '''Getting rid of containers''',
    url: '''https://github.com/flutter/flutter/pull/147432''',
    date: 'Apr 26 2024',
    diffs: (480, 428),
    refactor: true,
  ),
  PullRequest(
    title: '''Refactor `Material` build method''',
    url: '''https://github.com/flutter/flutter/pull/147430''',
    date: 'Apr 26 2024',
    diffs: (37, 92),
    refactor: true,
  ),
  PullRequest(
    title: '''Add default arguments to `AnimatedPhysicalModel`''',
    url: '''https://github.com/flutter/flutter/pull/147424''',
    date: 'Apr 26 2024',
    diffs: (49, 11),
    refactor: false,
  ),
  PullRequest(
    title: '''Switch to relevant `Remote` constructors''',
    url: '''https://github.com/flutter/flutter/pull/146773''',
    date: 'Apr 15 2024',
    diffs: (15, 51),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing control flow collections''',
    url: '''https://github.com/flutter/flutter/pull/146601''',
    date: 'Apr 10 2024',
    diffs: (276, 494),
    refactor: true,
  ),
  PullRequest(
    title: '''`flutter/lib/src/`: refactoring if-chains into switch expressions''',
    url: '''https://github.com/flutter/flutter/pull/146293''',
    date: 'Apr 04 2024',
    diffs: (111, 203),
    refactor: true,
  ),
  PullRequest(
    title: '''`WidgetState` mapping''',
    url: '''https://github.com/flutter/flutter/pull/146043''',
    date: 'Mar 30 2024',
    diffs: (305, 10),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing switch expressions in `flutter_tools/`''',
    url: '''https://github.com/flutter/flutter/pull/145632''',
    date: 'Mar 23 2024',
    diffs: (222, 409),
    refactor: true,
  ),
  PullRequest(
    title: '''Intensive `if` chain refactoring''',
    url: '''https://github.com/flutter/flutter/pull/145194''',
    date: 'Mar 15 2024',
    diffs: (98, 352),
    refactor: true,
  ),
  PullRequest(
    title: '''Turning `if` chains into shorter `switch` statements''',
    url: '''https://github.com/flutter/flutter/pull/144977''',
    date: 'Mar 12 2024',
    diffs: (141, 182),
    refactor: true,
  ),
  PullRequest(
    title: '''Refactoring `if` chains into `switch` statements''',
    url: '''https://github.com/flutter/flutter/pull/144905''',
    date: 'Mar 10 2024',
    diffs: (404, 349),
    refactor: true,
  ),
  PullRequest(
    title: '''Add platform check to `FocusManager` app lifecycle listener''',
    url: '''https://github.com/flutter/flutter/pull/144718''',
    date: 'Mar 06 2024',
    diffs: (51, 6),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing switch expressions in `flutter/test/`''',
    url: '''https://github.com/flutter/flutter/pull/144580''',
    date: 'Mar 05 2024',
    diffs: (115, 189),
    refactor: true,
  ),
  PullRequest(
    title: '''Add missing parameter to `TableBorder.symmetric`, and improve class constructors''',
    url: '''https://github.com/flutter/flutter/pull/144279''',
    date: 'Feb 28 2024',
    diffs: (196, 357),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in `rendering/`''',
    url: '''https://github.com/flutter/flutter/pull/143812''',
    date: 'Feb 21 2024',
    diffs: (366, 604),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing null-aware operators throughout the repository''',
    url: '''https://github.com/flutter/flutter/pull/143804''',
    date: 'Feb 21 2024',
    diffs: (93, 365),
    refactor: true,
  ),
  PullRequest(
    title: '''Allow `Listenable.merge()` to use any iterable''',
    url: '''https://github.com/flutter/flutter/pull/143675''',
    date: 'Feb 18 2024',
    diffs: (20, 5),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions: everything in `flutter/lib/src/`''',
    url: '''https://github.com/flutter/flutter/pull/143634''',
    date: 'Feb 17 2024',
    diffs: (503, 925),
    refactor: true,
  ),
  PullRequest(
    title: '''Implement `_suspendedNode` fix''',
    url: '''https://github.com/flutter/flutter/pull/143556''',
    date: 'Feb 16 2024',
    diffs: (2, 3),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions [refactoring `flutter/lib/src/`]''',
    url: '''https://github.com/flutter/flutter/pull/143496''',
    date: 'Feb 14 2024',
    diffs: (152, 305),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in `widgets/`''',
    url: '''https://github.com/flutter/flutter/pull/143293''',
    date: 'Feb 12 2024',
    diffs: (169, 306),
    refactor: true,
  ),
  PullRequest(
    title: '''Have `FocusManager` respond to app lifecycle state changes''',
    url: '''https://github.com/flutter/flutter/pull/142930''',
    date: 'Feb 05 2024',
    diffs: (102, 0),
    refactor: false,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in `lib/src/material/`''',
    url: '''https://github.com/flutter/flutter/pull/142793''',
    date: 'Feb 02 2024',
    diffs: (182, 339),
    refactor: true,
  ),
  PullRequest(
    title: '''Implement `switch` expressions in `lib/src/material/`''',
    url: '''https://github.com/flutter/flutter/pull/142634''',
    date: 'Jan 31 2024',
    diffs: (146, 256),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in `foundation/` and `material/`''',
    url: '''https://github.com/flutter/flutter/pull/142279''',
    date: 'Jan 26 2024',
    diffs: (115, 196),
    refactor: true,
  ),
  PullRequest(
    title: '''Implementing `switch` expressions in the `cupertino/` directory''',
    url: '''https://github.com/flutter/flutter/pull/141591''',
    date: 'Jan 16 2024',
    diffs: (78, 144),
    refactor: true,
  ),
  PullRequest(
    title: '''Implement `switch` expressions in `examples/` and `animation/`''',
    url: '''https://github.com/flutter/flutter/pull/139882''',
    date: 'Dec 10 2023',
    diffs: (33, 50),
    refactor: true,
  ),
  PullRequest(
    title: '''Implement `switch` expressions in `dev/`''',
    url: '''https://github.com/flutter/flutter/pull/139048''',
    date: 'Nov 27 2023',
    diffs: (117, 197),
    refactor: true,
  ),
];
