name: nate_thegrate
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.2.3
  flutter_hooks: ^0.20.5
  meta: ^1.12.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  graphql: ^5.1.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/times.ttf
        - asset: assets/fonts/timesbd.ttf
          weight: 700
        - asset: assets/fonts/timesi.ttf
          style: italic
        - asset: assets/fonts/timesbi.ttf
          weight: 700
          style: italic
    - family: gaegu
      fonts:
        - asset: assets/fonts/gaegu.ttf
        - asset: assets/fonts/gaegu_bold.ttf
          weight: 700
        - asset: assets/fonts/gaegu_light.ttf
          weight: 300
