name: nate_thegrate
description: "Nate's Flutter portfolio"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  flutter_hooks: ^0.20.5
  meta: ^1.15.0
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  graphql: ^5.1.3
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/times.ttf
        - asset: assets/fonts/timesbd.ttf
          weight: 700
    - family: gaegu
      fonts:
        - asset: assets/fonts/gaegu.ttf
        - asset: assets/fonts/gaegu_bold.ttf
          weight: 700
    - family: roboto mono
      fonts:
        - asset: assets/fonts/roboto_mono.ttf
    - family: annie use your telescope
      fonts:
        - asset: assets/fonts/annie_use_your_telescope.ttf
