name: nate_thegrate
description: "Nate's Flutter portfolio"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  flutter_hooks: ^0.20.5
  meta: ^1.15.0
  url_launcher: ^6.3.0
  collection_notifiers: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  graphql: ^5.1.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/times.ttf
        - asset: assets/fonts/timesbd.ttf
          weight: 700
    - family: gaegu
      fonts:
        - asset: assets/fonts/gaegu.ttf
        - asset: assets/fonts/gaegu_bold.ttf
          weight: 700
    - family: roboto mono
      fonts:
        - asset: assets/fonts/roboto_mono.ttf
    - family: annie use your telescope
      fonts:
        - asset: assets/fonts/annie_use_your_telescope.ttf
